services:
  lessons-create:
    container_name: lessons-create
    image: public.ecr.aws/lambda/go:latest
    command: create
    ports:
      - 8080:8080
    volumes:
      - ./bin:/var/task
      - ${HOME}/.aws/:/root/.aws
    restart: always
