services:
  lessons-create:
    container_name: lessons-create
    image: public.ecr.aws/lambda/go:latest
    command: create
    ports:
      - 8080:8080
    volumes:
      - ./bin:/var/task
      - ${HOME}/.aws/:/root/.aws
    links:
      - dynamodb
    restart: always
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    expose:
      - "8000"
      
